services:
  - type: web
    name: campus-connect-59ms
    runtime: docker
    plan: free
    dockerfilePath: ./campus_connect/Dockerfile
    dockerContext: ./campus_connect
    buildHook: |
      set -o errexit
      echo "--- Running build hook ---"
      php artisan migrate --force
      echo "--- Build hook finished ---"
