services:
  - type: web
    name: campus-connect-59ms
    runtime: docker
    plan: free
    dockerfilePath: ./campus_connect/Dockerfile
    dockerContext: ./campus_connect
    preDeployCommand: "php artisan migrate --force"
