services:
  - type: web
    name: campus-connect-59ms
    runtime: docker
    plan: free
    dockerfilePath: ./campus_connect/Dockerfile
    dockerContext: ./campus_connect
    preDeployCommand: |
      set -o errexit
      echo "--- Running pre-deploy commands ---"
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
      echo "--- Pre-deploy commands finished ---"
